fails:Exception#to_s returns self's message if set
fails:Exception#to_s calls #to_s on the message
